# Generated by Django 2.2 on 2021-08-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denglu',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ershoufang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
                ('position1', models.CharField(max_length=50)),
                ('position2', models.CharField(max_length=50)),
                ('position3', models.CharField(max_length=50)),
                ('houseInfo1', models.CharField(max_length=50)),
                ('houseInfo2', models.CharField(max_length=50)),
                ('houseInfo3', models.CharField(max_length=50)),
                ('totalPrice', models.IntegerField()),
                ('unitPrice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='newfang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position1', models.CharField(max_length=50)),
                ('position2', models.CharField(max_length=50)),
                ('position3', models.CharField(max_length=50)),
                ('houseinfo', models.CharField(max_length=50)),
                ('unitPrice', models.CharField(max_length=50)),
                ('totalPrice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='shoumai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('position1', models.CharField(max_length=50)),
                ('totalPrice', models.CharField(max_length=50)),
                ('size_room', models.CharField(max_length=50)),
                ('area_room', models.CharField(max_length=50)),
                ('num_room', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('minzu', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('picture', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='zufang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('position1', models.CharField(max_length=50)),
                ('position2', models.CharField(max_length=50)),
                ('position3', models.CharField(max_length=50)),
                ('totalPrice', models.IntegerField()),
                ('size_room', models.CharField(max_length=50)),
                ('area_room', models.CharField(max_length=50)),
                ('num_room', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='zulin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('position1', models.CharField(max_length=50)),
                ('totalPrice', models.CharField(max_length=50)),
                ('size_room', models.CharField(max_length=50)),
                ('area_room', models.CharField(max_length=50)),
                ('num_room', models.CharField(max_length=50)),
            ],
        ),
    ]
